### PR TITLE
Chore: Industrial CI

### PR DESCRIPTION
**Pull request by reinzor**
- Industrial CI for Kinetic and Melodic
- Updated README with build badge

@SteveMacenski as a user should authorize Travic CI on Github

### CODE REVIEW

**Comment by reinzor** [comment]
ping

**Comment by SteveMacenski** [comment]
@reinzor I could change the rosdistro config to add the pull request builder to this repo. Is there an advantage of running this in travis over that? 

https://github.com/ros/rosdistro/pull/21053

**Comment by reinzor** [comment]
I think that will be fine as well. I personally prefer Travis with industrial CI but both are fine. As long as we have some CI verification when doing PR's ;).

**Comment by SteveMacenski** [comment]
Fair enough, frankly this was a quick project as an intro to costmap layers and use for RADAR testing, I didn't expect others to use it. I'm _super_ glad you are though :-) I'll wait until we have confirmation from rosdistro that it's in before closing this PR. I'm also planning on releasing melodic binaries (seems like you might want them) and I'll add the melodic PR builder to this as well.

**Comment by SteveMacenski** [comment]
closing and reopening to see if CI kicks in

**Comment by SteveMacenski** [comment]
@reinzor found the issue, I have it setup to build PRs against master not kinetic devel. Will submit that change and we should be all set

**Comment by SteveMacenski** [comment]
Boom, works now!
Closing for _real_ now  :-) Thanks for the defensive measures!

I'm curious, are you running this on Melodic from your PR and everything is compiling? I can release Melodic binaries this week if it works out of the box now

**Comment by reinzor** [comment]
Thanks! We are currently transitioning to melodic, will let you know if everything works properly :)

**Pull request closed without merging**
